name: NuGet Generation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet 
    steps:

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Build nugets
        run: |
          dotnet pack -c Release -o out
                    
      - name: Install NuGet client
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Add private GitHub registry to NuGet
        run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/nmakhmutov/index.json" -UserName nmakhmutov -Password ${{ secrets.GT }}

      - name: Push generated package to GitHub registry
        run: nuget push ./out/*.nupkg -Source "GitHub" -SkipDuplicate
        
